### ISSUE TITLE
Transparency might be a touch too much

### ISSUE THREAD

**Issue by dasburninator** [eliteSchwein/acryl-fluidd-mainsail-theme#1]
I'm pretty sure its not me getting old. I asked an actual old person and they couldn't see anything at all.

It looks really good, but the transparency is a bit aggressive.

**Comment by eliteSchwein** [comment]
hey there, i will take a look and maybe change some stuff

**Comment by eliteSchwein** [comment]
i updated the colors, its now darker

**Comment by dasburninator** [comment]
That is much better!
